baseDir = "."

headerPath = "Apache-2.0.txt"

excludes = [
    # hidden files
    ".cargo",
    ".github",
    ".dockerignore",
    ".gitignore",
    ".gitattributes",
    ".editorconfig",

    "LICENSE",
    "Makefile",

    "examples/**",

    # docs and generated files
    "**/*.md",
    "**/*.hbs",
    "**/*.template",
    "**/*.cue",
    "**/*.json",
    "**/*.sql",
    "**/*.proto",
    "**/*.yml",
    "**/*.yaml",
    "**/*.toml",
    "**/*.lock",
    "**/*.yapf",
    "**/*.test",
    "**/*.txt",
]

[properties]
inceptionYear = 2021
copyrightOwner = "Datafuse Labs"
